Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pyodbc 
import pandas as pd
cnxn_str = ("Driver={odbc driver 17 for sql server};"
            "Server=DESKTOP-GVA3L0V\SQLEXPRESS;"
            "Database=prosain200411100082;"
            "Trusted_Connection=yes;")
cnxn = pyodbc.connect(cnxn_str)
cursor = cnxn.cursor()	
cursor.execute("SELECT * FROM iris_arff") 
row = cursor.fetchall() 
cursor.close()
data=[]
for i in row:
    data.append([i[0],i[1],i[2]])
df_sqlServer = pd.DataFrame(data, columns=['id','petalwidth','class'])
df_sqlServer
------------------


[0;31m[0m
[0;31mError[0mTraceback (most recent call last)
[0;32m<ipython-input-2-2663ed3f6e2e>[0m in [0;36m<cell line: 7>[0;34m()[0m
[1;32m      5[0m             [0;34m"Database=prosain200411100082;"[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m             "Trusted_Connection=yes;")
[0;32m----> 7[0;31m [0mcnxn[0m [0;34m=[0m [0mpyodbc[0m[0;34m.[0m[0mconnect[0m[0;34m([0m[0mcnxn_str[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0mcursor[0m [0;34m=[0m [0mcnxn[0m[0;34m.[0m[0mcursor[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0mcursor[0m[0;34m.[0m[0mexecute[0m[0;34m([0m[0;34m"SELECT * FROM iris_arff"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mError[0m: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'odbc driver 17 for sql server' : file not found (0) (SQLDriverConnect)")

